# LOAD DATA

## Imports

In [1]:
import sys
sys.path.append("..")

In [2]:
import pandas as pd
from data_to_db.functions import execute_mysql_command

pd.set_option('display.max_columns', None)

## Data

In [3]:
data = execute_mysql_command('SELECT * FROM student_data')
df = pd.DataFrame(data, columns=['id', 'Gender', 'Age', 'City', 'Profession', 'Academic_Pressure', 'Work_Pressure', 'CGPA', 'Study_Satisfaction', 'Job_Satisfaction', 'Sleep_Duration', 'Dietary_Habits', 'Degree', 'had_suicidal_thoughts', 'Work_Study_Hours',
'Financial_Stress','Family_History_of_Mental_Illness','Depression'])
df.set_index('id', inplace=True)
df

,Gender,Age,City,Profession,Academic_Pressure,Work_Pressure,CGPA,Study_Satisfaction,Job_Satisfaction,Sleep_Duration,Dietary_Habits,Degree,had_suicidal_thoughts,Work_Study_Hours,Financial_Stress,Family_History_of_Mental_Illness,Depression
id,,,,,,,,,,,,,,,,,
2,Male,33.00,Visakhapatnam,Student,5.00,0.00,8.97,2.00,0.00,5-6 hours,Healthy,B.Pharm,Yes,3.00,1.0,No,1
8,Female,24.00,Bangalore,Student,2.00,0.00,5.90,5.00,0.00,5-6 hours,Moderate,BSc,No,3.00,2.0,Yes,0
26,Male,31.00,Srinagar,Student,3.00,0.00,7.03,5.00,0.00,Less than 5 hours,Healthy,BA,No,9.00,1.0,Yes,0
30,Female,28.00,Varanasi,Student,3.00,0.00,5.59,2.00,0.00,7-8 hours,Moderate,BCA,Yes,4.00,5.0,Yes,1
32,Female,25.00,Jaipur,Student,4.00,0.00,8.13,3.00,0.00,5-6 hours,Moderate,M.Tech,Yes,1.00,1.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140685,Female,27.00,Surat,Student,5.00,0.00,5.75,5.00,0.00,5-6 hours,Unhealthy,Class 12,Yes,7.00,1.0,Yes,0
140686,Male,27.00,Ludhiana,Student,2.00,0.00,9.40,3.00,0.00,Less than 5 hours,Healthy,MSc,No,0.00,3.0,Yes,0
140689,Male,31.00,Faridabad,Student,3.00,0.00,6.61,4.00,0.00,5-6 hours,Unhealthy,MD,No,12.00,2.0,No,0
140690,Female,18.00,Ludhiana,Student,5.00,0.00,6.88,2.00,0.00,Less than 5 hours,Healthy,Class 12,Yes,10.00,5.0,No,1
140699,Male,27.00,Patna,Student,4.00,0.00,9.24,1.00,0.00,Less than 5 hours,Healthy,BCA,Yes,2.00,3.0,Yes,1

# DATA PREPARATION

## All Columns

In [4]:
df.dtypes

Gender                              object
Age                                 object
City                                object
Profession                          object
Academic_Pressure                   object
Work_Pressure                       object
CGPA                                object
Study_Satisfaction                  object
Job_Satisfaction                    object
Sleep_Duration                      object
Dietary_Habits                      object
Degree                              object
had_suicidal_thoughts               object
Work_Study_Hours                    object
Financial_Stress                    object
Family_History_of_Mental_Illness    object
Depression                           int64
dtype: object

In [5]:
print(df.shape)
df.isnull().sum()

(27901, 17)

Gender                              0
Age                                 0
City                                0
Profession                          0
Academic_Pressure                   0
Work_Pressure                       0
CGPA                                0
Study_Satisfaction                  0
Job_Satisfaction                    0
Sleep_Duration                      0
Dietary_Habits                      0
Degree                              0
had_suicidal_thoughts               0
Work_Study_Hours                    0
Financial_Stress                    0
Family_History_of_Mental_Illness    0
Depression                          0
dtype: int64

In [6]:
df.drop_duplicates(inplace=True)
print(df.shape)

(27901, 17)

## Gender

In [7]:
df.Gender.value_counts()

Gender
Male      15547
Female    12354
Name: count, dtype: int64

0 - male <br>
1 - female

In [8]:
df.Gender = df.Gender.apply(lambda x: 0 if x == 'Male' else 1)
df

,Gender,Age,City,Profession,Academic_Pressure,Work_Pressure,CGPA,Study_Satisfaction,Job_Satisfaction,Sleep_Duration,Dietary_Habits,Degree,had_suicidal_thoughts,Work_Study_Hours,Financial_Stress,Family_History_of_Mental_Illness,Depression
id,,,,,,,,,,,,,,,,,
2,0,33.00,Visakhapatnam,Student,5.00,0.00,8.97,2.00,0.00,5-6 hours,Healthy,B.Pharm,Yes,3.00,1.0,No,1
8,1,24.00,Bangalore,Student,2.00,0.00,5.90,5.00,0.00,5-6 hours,Moderate,BSc,No,3.00,2.0,Yes,0
26,0,31.00,Srinagar,Student,3.00,0.00,7.03,5.00,0.00,Less than 5 hours,Healthy,BA,No,9.00,1.0,Yes,0
30,1,28.00,Varanasi,Student,3.00,0.00,5.59,2.00,0.00,7-8 hours,Moderate,BCA,Yes,4.00,5.0,Yes,1
32,1,25.00,Jaipur,Student,4.00,0.00,8.13,3.00,0.00,5-6 hours,Moderate,M.Tech,Yes,1.00,1.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140685,1,27.00,Surat,Student,5.00,0.00,5.75,5.00,0.00,5-6 hours,Unhealthy,Class 12,Yes,7.00,1.0,Yes,0
140686,0,27.00,Ludhiana,Student,2.00,0.00,9.40,3.00,0.00,Less than 5 hours,Healthy,MSc,No,0.00,3.0,Yes,0
140689,0,31.00,Faridabad,Student,3.00,0.00,6.61,4.00,0.00,5-6 hours,Unhealthy,MD,No,12.00,2.0,No,0
140690,1,18.00,Ludhiana,Student,5.00,0.00,6.88,2.00,0.00,Less than 5 hours,Healthy,Class 12,Yes,10.00,5.0,No,1
140699,0,27.00,Patna,Student,4.00,0.00,9.24,1.00,0.00,Less than 5 hours,Healthy,BCA,Yes,2.00,3.0,Yes,1

## Age

In [9]:
df.Age.dtype

dtype('O')

In [10]:
df.Age = df.Age.astype(int)
df

,Gender,Age,City,Profession,Academic_Pressure,Work_Pressure,CGPA,Study_Satisfaction,Job_Satisfaction,Sleep_Duration,Dietary_Habits,Degree,had_suicidal_thoughts,Work_Study_Hours,Financial_Stress,Family_History_of_Mental_Illness,Depression
id,,,,,,,,,,,,,,,,,
2,0,33,Visakhapatnam,Student,5.00,0.00,8.97,2.00,0.00,5-6 hours,Healthy,B.Pharm,Yes,3.00,1.0,No,1
8,1,24,Bangalore,Student,2.00,0.00,5.90,5.00,0.00,5-6 hours,Moderate,BSc,No,3.00,2.0,Yes,0
26,0,31,Srinagar,Student,3.00,0.00,7.03,5.00,0.00,Less than 5 hours,Healthy,BA,No,9.00,1.0,Yes,0
30,1,28,Varanasi,Student,3.00,0.00,5.59,2.00,0.00,7-8 hours,Moderate,BCA,Yes,4.00,5.0,Yes,1
32,1,25,Jaipur,Student,4.00,0.00,8.13,3.00,0.00,5-6 hours,Moderate,M.Tech,Yes,1.00,1.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140685,1,27,Surat,Student,5.00,0.00,5.75,5.00,0.00,5-6 hours,Unhealthy,Class 12,Yes,7.00,1.0,Yes,0
140686,0,27,Ludhiana,Student,2.00,0.00,9.40,3.00,0.00,Less than 5 hours,Healthy,MSc,No,0.00,3.0,Yes,0
140689,0,31,Faridabad,Student,3.00,0.00,6.61,4.00,0.00,5-6 hours,Unhealthy,MD,No,12.00,2.0,No,0
140690,1,18,Ludhiana,Student,5.00,0.00,6.88,2.00,0.00,Less than 5 hours,Healthy,Class 12,Yes,10.00,5.0,No,1
140699,0,27,Patna,Student,4.00,0.00,9.24,1.00,0.00,Less than 5 hours,Healthy,BCA,Yes,2.00,3.0,Yes,1

## City

In [11]:
df_cleaned = df.drop(['City'], axis=1)
df_cleaned

,Gender,Age,Profession,Academic_Pressure,Work_Pressure,CGPA,Study_Satisfaction,Job_Satisfaction,Sleep_Duration,Dietary_Habits,Degree,had_suicidal_thoughts,Work_Study_Hours,Financial_Stress,Family_History_of_Mental_Illness,Depression
id,,,,,,,,,,,,,,,,
2,0,33,Student,5.00,0.00,8.97,2.00,0.00,5-6 hours,Healthy,B.Pharm,Yes,3.00,1.0,No,1
8,1,24,Student,2.00,0.00,5.90,5.00,0.00,5-6 hours,Moderate,BSc,No,3.00,2.0,Yes,0
26,0,31,Student,3.00,0.00,7.03,5.00,0.00,Less than 5 hours,Healthy,BA,No,9.00,1.0,Yes,0
30,1,28,Student,3.00,0.00,5.59,2.00,0.00,7-8 hours,Moderate,BCA,Yes,4.00,5.0,Yes,1
32,1,25,Student,4.00,0.00,8.13,3.00,0.00,5-6 hours,Moderate,M.Tech,Yes,1.00,1.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140685,1,27,Student,5.00,0.00,5.75,5.00,0.00,5-6 hours,Unhealthy,Class 12,Yes,7.00,1.0,Yes,0
140686,0,27,Student,2.00,0.00,9.40,3.00,0.00,Less than 5 hours,Healthy,MSc,No,0.00,3.0,Yes,0
140689,0,31,Student,3.00,0.00,6.61,4.00,0.00,5-6 hours,Unhealthy,MD,No,12.00,2.0,No,0
140690,1,18,Student,5.00,0.00,6.88,2.00,0.00,Less than 5 hours,Healthy,Class 12,Yes,10.00,5.0,No,1
140699,0,27,Student,4.00,0.00,9.24,1.00,0.00,Less than 5 hours,Healthy,BCA,Yes,2.00,3.0,Yes,1

## Profession

In [12]:
df_cleaned.Profession.unique()

array(['Student', 'Civil Engineer', 'Architect', 'UX/UI Designer',
       'Digital Marketer', 'Content Writer', 'Educational Consultant',
       'Teacher', 'Manager', 'Chef', 'Doctor', 'Lawyer', 'Entrepreneur',
       'Pharmacist'], dtype=object)

0 - student <br>
1 - other

In [13]:
df_cleaned.Profession = df_cleaned.Profession.apply(
    lambda x: 0 if x == 'Student' else 1)
df_cleaned

,Gender,Age,Profession,Academic_Pressure,Work_Pressure,CGPA,Study_Satisfaction,Job_Satisfaction,Sleep_Duration,Dietary_Habits,Degree,had_suicidal_thoughts,Work_Study_Hours,Financial_Stress,Family_History_of_Mental_Illness,Depression
id,,,,,,,,,,,,,,,,
2,0,33,0,5.00,0.00,8.97,2.00,0.00,5-6 hours,Healthy,B.Pharm,Yes,3.00,1.0,No,1
8,1,24,0,2.00,0.00,5.90,5.00,0.00,5-6 hours,Moderate,BSc,No,3.00,2.0,Yes,0
26,0,31,0,3.00,0.00,7.03,5.00,0.00,Less than 5 hours,Healthy,BA,No,9.00,1.0,Yes,0
30,1,28,0,3.00,0.00,5.59,2.00,0.00,7-8 hours,Moderate,BCA,Yes,4.00,5.0,Yes,1
32,1,25,0,4.00,0.00,8.13,3.00,0.00,5-6 hours,Moderate,M.Tech,Yes,1.00,1.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140685,1,27,0,5.00,0.00,5.75,5.00,0.00,5-6 hours,Unhealthy,Class 12,Yes,7.00,1.0,Yes,0
140686,0,27,0,2.00,0.00,9.40,3.00,0.00,Less than 5 hours,Healthy,MSc,No,0.00,3.0,Yes,0
140689,0,31,0,3.00,0.00,6.61,4.00,0.00,5-6 hours,Unhealthy,MD,No,12.00,2.0,No,0
140690,1,18,0,5.00,0.00,6.88,2.00,0.00,Less than 5 hours,Healthy,Class 12,Yes,10.00,5.0,No,1
140699,0,27,0,4.00,0.00,9.24,1.00,0.00,Less than 5 hours,Healthy,BCA,Yes,2.00,3.0,Yes,1

Delete column because the data is very unbalanced

In [14]:
df_cleaned.Profession.value_counts()

Profession
0    27870
1       31
Name: count, dtype: int64

In [15]:
df_cleaned.drop(['Profession'], axis=1, inplace= True)
df_cleaned

,Gender,Age,Academic_Pressure,Work_Pressure,CGPA,Study_Satisfaction,Job_Satisfaction,Sleep_Duration,Dietary_Habits,Degree,had_suicidal_thoughts,Work_Study_Hours,Financial_Stress,Family_History_of_Mental_Illness,Depression
id,,,,,,,,,,,,,,,
2,0,33,5.00,0.00,8.97,2.00,0.00,5-6 hours,Healthy,B.Pharm,Yes,3.00,1.0,No,1
8,1,24,2.00,0.00,5.90,5.00,0.00,5-6 hours,Moderate,BSc,No,3.00,2.0,Yes,0
26,0,31,3.00,0.00,7.03,5.00,0.00,Less than 5 hours,Healthy,BA,No,9.00,1.0,Yes,0
30,1,28,3.00,0.00,5.59,2.00,0.00,7-8 hours,Moderate,BCA,Yes,4.00,5.0,Yes,1
32,1,25,4.00,0.00,8.13,3.00,0.00,5-6 hours,Moderate,M.Tech,Yes,1.00,1.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140685,1,27,5.00,0.00,5.75,5.00,0.00,5-6 hours,Unhealthy,Class 12,Yes,7.00,1.0,Yes,0
140686,0,27,2.00,0.00,9.40,3.00,0.00,Less than 5 hours,Healthy,MSc,No,0.00,3.0,Yes,0
140689,0,31,3.00,0.00,6.61,4.00,0.00,5-6 hours,Unhealthy,MD,No,12.00,2.0,No,0
140690,1,18,5.00,0.00,6.88,2.00,0.00,Less than 5 hours,Healthy,Class 12,Yes,10.00,5.0,No,1
140699,0,27,4.00,0.00,9.24,1.00,0.00,Less than 5 hours,Healthy,BCA,Yes,2.00,3.0,Yes,1

## Sleep duration

In [16]:
df_cleaned.Sleep_Duration.unique()

array(['5-6 hours', 'Less than 5 hours', '7-8 hours', 'More than 8 hours',
       'Others'], dtype=object)

In [17]:
df_cleaned.Sleep_Duration.value_counts()

Sleep_Duration
Less than 5 hours    8310
7-8 hours            7346
5-6 hours            6183
More than 8 hours    6044
Others                 18
Name: count, dtype: int64

In [18]:
df_cleaned.query('Sleep_Duration != "Others"', inplace=True)

In [19]:
from sklearn.preprocessing import OneHotEncoder

In [20]:
encoder = OneHotEncoder(sparse_output=False)
encoded_data = encoder.fit_transform(df_cleaned[['Sleep_Duration']])
encoded_df = pd.DataFrame(
    encoded_data, columns=encoder.get_feature_names_out(['Sleep_Duration']))
encoded_df.index = df_cleaned.index
encoded_df

,Sleep_Duration_5-6 hours,Sleep_Duration_7-8 hours,Sleep_Duration_Less than 5 hours,Sleep_Duration_More than 8 hours
id,,,,
2,1.0,0.0,0.0,0.0
8,1.0,0.0,0.0,0.0
26,0.0,0.0,1.0,0.0
30,0.0,1.0,0.0,0.0
32,1.0,0.0,0.0,0.0
...,...,...,...,...
140685,1.0,0.0,0.0,0.0
140686,0.0,0.0,1.0,0.0
140689,1.0,0.0,0.0,0.0
140690,0.0,0.0,1.0,0.0
140699,0.0,0.0,1.0,0.0

In [21]:
df_cleaned = pd.concat([df_cleaned, encoded_df], axis=1)
df_cleaned.drop(['Sleep_Duration'], axis=1, inplace=True)
df_cleaned

,Gender,Age,Academic_Pressure,Work_Pressure,CGPA,Study_Satisfaction,Job_Satisfaction,Dietary_Habits,Degree,had_suicidal_thoughts,Work_Study_Hours,Financial_Stress,Family_History_of_Mental_Illness,Depression,Sleep_Duration_5-6 hours,Sleep_Duration_7-8 hours,Sleep_Duration_Less than 5 hours,Sleep_Duration_More than 8 hours
id,,,,,,,,,,,,,,,,,,
2,0,33,5.00,0.00,8.97,2.00,0.00,Healthy,B.Pharm,Yes,3.00,1.0,No,1,1.0,0.0,0.0,0.0
8,1,24,2.00,0.00,5.90,5.00,0.00,Moderate,BSc,No,3.00,2.0,Yes,0,1.0,0.0,0.0,0.0
26,0,31,3.00,0.00,7.03,5.00,0.00,Healthy,BA,No,9.00,1.0,Yes,0,0.0,0.0,1.0,0.0
30,1,28,3.00,0.00,5.59,2.00,0.00,Moderate,BCA,Yes,4.00,5.0,Yes,1,0.0,1.0,0.0,0.0
32,1,25,4.00,0.00,8.13,3.00,0.00,Moderate,M.Tech,Yes,1.00,1.0,No,0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140685,1,27,5.00,0.00,5.75,5.00,0.00,Unhealthy,Class 12,Yes,7.00,1.0,Yes,0,1.0,0.0,0.0,0.0
140686,0,27,2.00,0.00,9.40,3.00,0.00,Healthy,MSc,No,0.00,3.0,Yes,0,0.0,0.0,1.0,0.0
140689,0,31,3.00,0.00,6.61,4.00,0.00,Unhealthy,MD,No,12.00,2.0,No,0,1.0,0.0,0.0,0.0
140690,1,18,5.00,0.00,6.88,2.00,0.00,Healthy,Class 12,Yes,10.00,5.0,No,1,0.0,0.0,1.0,0.0
140699,0,27,4.00,0.00,9.24,1.00,0.00,Healthy,BCA,Yes,2.00,3.0,Yes,1,0.0,0.0,1.0,0.0

## Processing numeric columns

In [22]:
from sklearn.preprocessing import StandardScaler

In [23]:
df_cleaned['Financial_Stress'].unique()

array(['1.0', '2.0', '5.0', '3.0', '4.0', '?'], dtype=object)

In [24]:
columns_to_process = ['Age', 'Academic_Pressure',
                      'Work_Pressure', 'CGPA', 'Study_Satisfaction', 'Job_Satisfaction', 'Work_Study_Hours', 'Financial_Stress']

df_cleaned.query('Financial_Stress != "?"', inplace=True)
df_cleaned[columns_to_process] = df_cleaned[columns_to_process].astype(float)

df_cleaned['Financial_Stress'].unique()

array([1., 2., 5., 3., 4.])

In [25]:
scaler = StandardScaler()
df_num_processed = pd.DataFrame(scaler.fit_transform(df_cleaned[columns_to_process]), columns= columns_to_process)
df_num_processed.index = df_cleaned.index
df_cleaned[columns_to_process] = df_num_processed[columns_to_process]
df_cleaned

,Gender,Age,Academic_Pressure,Work_Pressure,CGPA,Study_Satisfaction,Job_Satisfaction,Dietary_Habits,Degree,had_suicidal_thoughts,Work_Study_Hours,Financial_Stress,Family_History_of_Mental_Illness,Depression,Sleep_Duration_5-6 hours,Sleep_Duration_7-8 hours,Sleep_Duration_Less than 5 hours,Sleep_Duration_More than 8 hours
id,,,,,,,,,,,,,,,,,,
2,0,1.463374,1.345217,-0.00978,0.893358,-0.693493,-0.015345,Healthy,B.Pharm,Yes,-1.121284,-1.489038,No,1,1.0,0.0,0.0,0.0
8,1,-0.371245,-0.826029,-0.00978,-1.194180,1.510716,-0.015345,Moderate,BSc,No,-1.121284,-0.793282,Yes,0,1.0,0.0,0.0,0.0
26,0,1.055681,-0.102280,-0.00978,-0.425803,1.510716,-0.015345,Healthy,BA,No,0.497192,-1.489038,Yes,0,0.0,0.0,1.0,0.0
30,1,0.444141,-0.102280,-0.00978,-1.404974,-0.693493,-0.015345,Moderate,BCA,Yes,-0.851538,1.293986,Yes,1,0.0,1.0,0.0,0.0
32,1,-0.167398,0.621468,-0.00978,0.322175,0.041243,-0.015345,Moderate,M.Tech,Yes,-1.660776,-1.489038,No,0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140685,1,0.240295,1.345217,-0.00978,-1.296177,1.510716,-0.015345,Unhealthy,Class 12,Yes,-0.042300,-1.489038,Yes,0,1.0,0.0,0.0,0.0
140686,0,0.240295,-0.826029,-0.00978,1.185749,0.041243,-0.015345,Healthy,MSc,No,-1.930522,-0.097526,Yes,0,0.0,0.0,1.0,0.0
140689,0,1.055681,-0.102280,-0.00978,-0.711394,0.775980,-0.015345,Unhealthy,MD,No,1.306430,-0.793282,No,0,1.0,0.0,0.0,0.0
140690,1,-1.594324,1.345217,-0.00978,-0.527800,-0.693493,-0.015345,Healthy,Class 12,Yes,0.766938,1.293986,No,1,0.0,0.0,1.0,0.0
140699,0,0.240295,0.621468,-0.00978,1.076953,-1.428230,-0.015345,Healthy,BCA,Yes,-1.391030,-0.097526,Yes,1,0.0,0.0,1.0,0.0

## Dietary habits

In [26]:
df_cleaned['Dietary_Habits'].value_counts()

Dietary_Habits
Unhealthy    10308
Moderate      9914
Healthy       7646
Others          12
Name: count, dtype: int64

In [27]:
df_cleaned.query('Dietary_Habits != "Others"', inplace=True)
print(df_cleaned.shape)
df_cleaned['Dietary_Habits'].value_counts()

(27868, 18)

Dietary_Habits
Unhealthy    10308
Moderate      9914
Healthy       7646
Name: count, dtype: int64

In [28]:
encoder_data_dietary = encoder.fit_transform(df_cleaned[['Dietary_Habits']])
encoder_df_dietary = pd.DataFrame(encoder_data_dietary,
                          columns=encoder.get_feature_names_out())
encoder_df_dietary.index = df_cleaned.index
df_cleaned = pd.concat([df_cleaned, encoder_df_dietary], axis=1)
df_cleaned.drop(['Dietary_Habits'], axis = 1, inplace=True)

## Degree

In [29]:
df_cleaned.Degree.value_counts()

Degree
Class 12    6079
B.Ed        1864
B.Com       1504
B.Arch      1476
BCA         1431
MSc         1189
B.Tech      1151
MCA         1041
M.Tech      1020
BHM          925
BSc          886
M.Ed         819
B.Pharm      809
M.Com        734
BBA          696
MBBS         695
LLB          670
BE           611
BA           597
M.Pharm      581
MD           572
MBA          561
MA           544
PhD          520
LLM          482
MHM          191
ME           185
Others        35
Name: count, dtype: int64

In [30]:
df_cleaned.query('Degree != "Others"', inplace=True)
df_cleaned['Degree'].value_counts()

Degree
Class 12    6079
B.Ed        1864
B.Com       1504
B.Arch      1476
BCA         1431
MSc         1189
B.Tech      1151
MCA         1041
M.Tech      1020
BHM          925
BSc          886
M.Ed         819
B.Pharm      809
M.Com        734
BBA          696
MBBS         695
LLB          670
BE           611
BA           597
M.Pharm      581
MD           572
MBA          561
MA           544
PhD          520
LLM          482
MHM          191
ME           185
Name: count, dtype: int64

In [31]:
encoder_data_degree = encoder.fit_transform(df_cleaned[['Degree']])
encoder_df_degree = pd.DataFrame(encoder_data_degree,
                                  columns=encoder.get_feature_names_out())
encoder_df_degree.index = df_cleaned.index
df_cleaned = pd.concat([df_cleaned, encoder_df_degree], axis=1)
df_cleaned.drop(['Degree'], axis=1, inplace=True)
df_cleaned

,Gender,Age,Academic_Pressure,Work_Pressure,CGPA,Study_Satisfaction,Job_Satisfaction,had_suicidal_thoughts,Work_Study_Hours,Financial_Stress,Family_History_of_Mental_Illness,Depression,Sleep_Duration_5-6 hours,Sleep_Duration_7-8 hours,Sleep_Duration_Less than 5 hours,Sleep_Duration_More than 8 hours,Dietary_Habits_Healthy,Dietary_Habits_Moderate,Dietary_Habits_Unhealthy,Degree_B.Arch,Degree_B.Com,Degree_B.Ed,Degree_B.Pharm,Degree_B.Tech,Degree_BA,Degree_BBA,Degree_BCA,Degree_BE,Degree_BHM,Degree_BSc,Degree_Class 12,Degree_LLB,Degree_LLM,Degree_M.Com,Degree_M.Ed,Degree_M.Pharm,Degree_M.Tech,Degree_MA,Degree_MBA,Degree_MBBS,Degree_MCA,Degree_MD,Degree_ME,Degree_MHM,Degree_MSc,Degree_PhD
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2,0,1.463374,1.345217,-0.00978,0.893358,-0.693493,-0.015345,Yes,-1.121284,-1.489038,No,1,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,1,-0.371245,-0.826029,-0.00978,-1.194180,1.510716,-0.015345,No,-1.121284,-0.793282,Yes,0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,0,1.055681,-0.102280,-0.00978,-0.425803,1.510716,-0.015345,No,0.497192,-1.489038,Yes,0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30,1,0.444141,-0.102280,-0.00978,-1.404974,-0.693493,-0.015345,Yes,-0.851538,1.293986,Yes,1,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32,1,-0.167398,0.621468,-0.00978,0.322175,0.041243,-0.015345,Yes,-1.660776,-1.489038,No,0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140685,1,0.240295,1.345217,-0.00978,-1.296177,1.510716,-0.015345,Yes,-0.042300,-1.489038,Yes,0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
140686,0,0.240295,-0.826029,-0.00978,1.185749,0.041243,-0.015345,No,-1.930522,-0.097526,Yes,0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
140689,0,1.055681,-0.102280,-0.00978,-0.711394,0.775980,-0.015345,No,1.306430,-0.793282,No,0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
140690,1,-1.594324,1.345217,-0.00978,-0.527800,-0.693493,-0.015345,Yes,0.766938,1.293986,No,1,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
140699,0,0.240295,0.621468,-0.00978,1.076953,-1.428230,-0.015345,Yes,-1.391030,-0.097526,Yes,1,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## Had suicidal thoughts

In [32]:
df_cleaned['had_suicidal_thoughts'].value_counts()

had_suicidal_thoughts
Yes    17615
No     10218
Name: count, dtype: int64

0 - No <br>
1 - Yes

In [33]:
df_cleaned['had_suicidal_thoughts'] = df_cleaned['had_suicidal_thoughts'].apply(lambda x: 1 if x == 'Yes' else 0)
df_cleaned

,Gender,Age,Academic_Pressure,Work_Pressure,CGPA,Study_Satisfaction,Job_Satisfaction,had_suicidal_thoughts,Work_Study_Hours,Financial_Stress,Family_History_of_Mental_Illness,Depression,Sleep_Duration_5-6 hours,Sleep_Duration_7-8 hours,Sleep_Duration_Less than 5 hours,Sleep_Duration_More than 8 hours,Dietary_Habits_Healthy,Dietary_Habits_Moderate,Dietary_Habits_Unhealthy,Degree_B.Arch,Degree_B.Com,Degree_B.Ed,Degree_B.Pharm,Degree_B.Tech,Degree_BA,Degree_BBA,Degree_BCA,Degree_BE,Degree_BHM,Degree_BSc,Degree_Class 12,Degree_LLB,Degree_LLM,Degree_M.Com,Degree_M.Ed,Degree_M.Pharm,Degree_M.Tech,Degree_MA,Degree_MBA,Degree_MBBS,Degree_MCA,Degree_MD,Degree_ME,Degree_MHM,Degree_MSc,Degree_PhD
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2,0,1.463374,1.345217,-0.00978,0.893358,-0.693493,-0.015345,1,-1.121284,-1.489038,No,1,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,1,-0.371245,-0.826029,-0.00978,-1.194180,1.510716,-0.015345,0,-1.121284,-0.793282,Yes,0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,0,1.055681,-0.102280,-0.00978,-0.425803,1.510716,-0.015345,0,0.497192,-1.489038,Yes,0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30,1,0.444141,-0.102280,-0.00978,-1.404974,-0.693493,-0.015345,1,-0.851538,1.293986,Yes,1,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32,1,-0.167398,0.621468,-0.00978,0.322175,0.041243,-0.015345,1,-1.660776,-1.489038,No,0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140685,1,0.240295,1.345217,-0.00978,-1.296177,1.510716,-0.015345,1,-0.042300,-1.489038,Yes,0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
140686,0,0.240295,-0.826029,-0.00978,1.185749,0.041243,-0.015345,0,-1.930522,-0.097526,Yes,0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
140689,0,1.055681,-0.102280,-0.00978,-0.711394,0.775980,-0.015345,0,1.306430,-0.793282,No,0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
140690,1,-1.594324,1.345217,-0.00978,-0.527800,-0.693493,-0.015345,1,0.766938,1.293986,No,1,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
140699,0,0.240295,0.621468,-0.00978,1.076953,-1.428230,-0.015345,1,-1.391030,-0.097526,Yes,1,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## Family history of mental illness

In [34]:
df_cleaned['Family_History_of_Mental_Illness'].value_counts()

Family_History_of_Mental_Illness
No     14359
Yes    13474
Name: count, dtype: int64

0 - No <br>
1 - Yes

In [35]:
df_cleaned['Family_History_of_Mental_Illness'] = df_cleaned['Family_History_of_Mental_Illness'].apply(
    lambda x: 1 if x == 'Yes' else 0)
df_cleaned

,Gender,Age,Academic_Pressure,Work_Pressure,CGPA,Study_Satisfaction,Job_Satisfaction,had_suicidal_thoughts,Work_Study_Hours,Financial_Stress,Family_History_of_Mental_Illness,Depression,Sleep_Duration_5-6 hours,Sleep_Duration_7-8 hours,Sleep_Duration_Less than 5 hours,Sleep_Duration_More than 8 hours,Dietary_Habits_Healthy,Dietary_Habits_Moderate,Dietary_Habits_Unhealthy,Degree_B.Arch,Degree_B.Com,Degree_B.Ed,Degree_B.Pharm,Degree_B.Tech,Degree_BA,Degree_BBA,Degree_BCA,Degree_BE,Degree_BHM,Degree_BSc,Degree_Class 12,Degree_LLB,Degree_LLM,Degree_M.Com,Degree_M.Ed,Degree_M.Pharm,Degree_M.Tech,Degree_MA,Degree_MBA,Degree_MBBS,Degree_MCA,Degree_MD,Degree_ME,Degree_MHM,Degree_MSc,Degree_PhD
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2,0,1.463374,1.345217,-0.00978,0.893358,-0.693493,-0.015345,1,-1.121284,-1.489038,0,1,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,1,-0.371245,-0.826029,-0.00978,-1.194180,1.510716,-0.015345,0,-1.121284,-0.793282,1,0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,0,1.055681,-0.102280,-0.00978,-0.425803,1.510716,-0.015345,0,0.497192,-1.489038,1,0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30,1,0.444141,-0.102280,-0.00978,-1.404974,-0.693493,-0.015345,1,-0.851538,1.293986,1,1,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32,1,-0.167398,0.621468,-0.00978,0.322175,0.041243,-0.015345,1,-1.660776,-1.489038,0,0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140685,1,0.240295,1.345217,-0.00978,-1.296177,1.510716,-0.015345,1,-0.042300,-1.489038,1,0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
140686,0,0.240295,-0.826029,-0.00978,1.185749,0.041243,-0.015345,0,-1.930522,-0.097526,1,0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
140689,0,1.055681,-0.102280,-0.00978,-0.711394,0.775980,-0.015345,0,1.306430,-0.793282,0,0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
140690,1,-1.594324,1.345217,-0.00978,-0.527800,-0.693493,-0.015345,1,0.766938,1.293986,0,1,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
140699,0,0.240295,0.621468,-0.00978,1.076953,-1.428230,-0.015345,1,-1.391030,-0.097526,1,1,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# SAVE PREPARED DATA

In [40]:
df_cleaned.to_csv(path_or_buf='../data/prepared_data.csv')